query Articles($id: ID!) {
    articles(where: { id: $id }) {
        id
        title
        slug
        body
        created_at
        excerpt
        SEO {
            id
            description
            title
        }
        image {
            url
            name
            width
            height
        }
        categories {
            name
            id
        }
    }
}
