query Articles($id: ID!) {
    articles(where: { slug: $id }) {
        id
        title
        slug
        body
        created_at
        image {
            url
            name
            width
            height
        }
        categories {
            name
            id
        }
    }
}
