query Products {
	products (limit: 3000){
    id
    name
    updated_at
    slug
    created_at
    description
    product_category{
      name
      id
    }
    images {
      url
      name
    }
  }
}