query ProductCategories($id: String!) {
    productCategories(where: { slug: $id }) {
        id
        name
        slug
        products {
            id
            name
            description
            product_category {
                name
                id
                slug
            }
            created_at
            updated_at
            slug
            images {
                url
            }
        }
    }
}
