query ProductCategories($id: ID!) {
    productCategories(where: { id: $id }) {
        id
        name
        slug
        products {
            id
            name
            product_category {
                name
            }
            created_at
            updated_at
            slug
            images {
                url
            }
        }
    }
}
