query Products($id: ID!) {
    products(where: { slug: $id }) {
        id
        name
        slug
        description
        product_details
        created_at
        product_category{
            name
            slug
            id
        }
        product_sub_category {
            id
            slug
            name
            product_category {
                id
                name
                slug
            }
        }
        downloads {
            id
            name
            file {
                url
                size
                alternativeText
                caption
            }
        }
        product_files {
            id
            name
            file {
                id
                name
                url
                size
                alternativeText
                caption
            }
        }
        product_videos {
            id
            name
            url

        }
        images {
            id
            name
            url
            width
            height
        }
    }
}
