query ProductCategories($id: ID!) {
    subProductCategories(where: { slug: $id }) {
        id
        name
        slug
        products {
            id
            name
            description
            product_category {
                name
                slug
                id
            }
            created_at
            updated_at
            slug
            images {
                url
            }
        }
    }
}
