query Solutions($id: ID!) {
    solutions(where: { slug: $id }) {
        id
        title
        slug
        description
        image {
            url
            name
        }
        content
    }
}
