query DownloadCenters{
    downloadCenters {
        id
        name
        download {
            id
            name
            file {
                id
                name
                updated_at
                size
                url
                ext
                caption
            }
        }
    }
}
