query HomePages {
    homePages {
        sliders {
            id
            name
            url
            image {
                url
                name
            }
        }
        partners {
            name
            image {
                url
            }
        }
    }
}
