query EcommerceImages {
    ecommerceImages {
        hero_carousel {
            id
            name
            image {
                id
                url
            }
        }
        sub_homepage_images {
            id
            name
            image {
                id
                url
            }
        }
        mid_page_images {
            id
            name
            image {
                id
                url
            }
        }
        homepage_array {
            id
            name
            image {
                id
                url
            }
        }
        shop_page_images {
            id
            name
            image {
                id
                url
            }
        }
    }
}
